In [14]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

text = ["London Paris London","Paris Paris London"]
cv = CountVectorizer()

count_matrix = cv.fit_transform(text)

#print count_matrix.toarray()
similarity_scores = cosine_similarity(count_matrix)

print(similarity_scores)

[[1.  0.8]
 [0.8 1. ]]
[[1.  0.8]
 [0.8 1. ]]


In [15]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [17]:
def get_title_from_index(index):
	return df[df.index == index]["title"].values[0]

def get_index_from_title(title):
	return df[df.title == title]["index"].values[0]

In [18]:
df = pd.read_csv("../content/drive/MyDrive/movie_dataset.csv")

In [19]:
features = ['keywords','cast','genres','director']

In [20]:
for feature in features:
	df[feature] = df[feature].fillna('')

def combine_features(row):
	try:
		return row['keywords'] +" "+row['cast']+" "+row["genres"]+" "+row["director"]
	except:
		print("Error:",row)

df["combined_features"] = df.apply(combine_features,axis=1)

print("Combined Features:",df["combined_features"].head())

Combined Features: 0    culture clash future space war space colony so...
1    ocean drug abuse exotic island east india trad...
2    spy based on novel secret agent sequel mi6 Dan...
3    dc comics crime fighter terrorist secret ident...
4    based on novel mars medallion space travel pri...
Name: combined_features, dtype: object


In [22]:
cv = CountVectorizer()

count_matrix = cv.fit_transform(df["combined_features"])

cosine_sim = cosine_similarity(count_matrix)
movie_user_likes = "The Avengers"


In [23]:
cv = CountVectorizer()

count_matrix = cv.fit_transform(df["combined_features"])

cosine_sim = cosine_similarity(count_matrix)
movie_user_likes = "The Avengers"


In [24]:
#Let's Inspect the vote_average feature and check if there are any null values. Looks like it is clean.
df["vote_average"].unique()

array([ 7.2,  6.9,  6.3,  7.6,  6.1,  5.9,  7.4,  7.3,  5.7,  5.4,  7. ,
        6.5,  6.4,  6.2,  7.1,  5.8,  6.6,  7.5,  5.5,  6.7,  6.8,  6. ,
        5.1,  7.8,  5.6,  5.2,  8.2,  7.7,  5.3,  8. ,  4.8,  4.9,  7.9,
        8.1,  4.7,  5. ,  4.2,  4.4,  4.1,  3.7,  3.6,  3. ,  3.9,  4.3,
        4.5,  3.4,  4.6,  8.3,  3.5,  4. ,  2.3,  3.2,  0. ,  3.8,  2.9,
        8.5,  1.9,  3.1,  3.3,  2.2,  0.5,  9.3,  8.4,  2.7, 10. ,  1. ,
        2. ,  2.8,  9.5,  2.6,  2.4])

In [26]:
movie_index = get_index_from_title(movie_user_likes)
similar_movies =  list(enumerate(cosine_sim[movie_index]))

sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse=True)

In [27]:
i=0
print("Top 10 similar movies to "+movie_user_likes+" are:\n")
for element in sorted_similar_movies:
    print(get_title_from_index(element[0]))
    i=i+1
    if i>10:
        break

Top 10 similar movies to The Avengers are:

The Avengers
Avengers: Age of Ultron
Iron Man 2
Captain America: The Winter Soldier
Captain America: Civil War
Thor: The Dark World
The Incredible Hulk
Ant-Man
X-Men
X2
Captain America: The First Avenger


In [28]:



movies = [
    "Stiff Upper Lips",
    "Dancer, Texas Pop. 81",
    "Me You and Five Bucks",
    "Little Big Top",
    "Sardaarji",
    "One Man's Hero",
    "The Shawshank Redemption",
    "There Goes My Baby",
    "The Prisoner of Zenda",
    "The Godfather",
    "Whiplash"
]

ratings = {}  # Define the ratings dictionary

print("Please rate the following movies out of 10:")

for movie in movies:
    rating = input(f"Rate '{movie}': ")
    try:
        rating = float(rating)
        if rating < 0 or rating > 10:
            raise ValueError("Rating should be between 0 and 10")
        ratings[movie] = rating
    except ValueError:
        print("Invalid rating! Please enter a number between 0 and 10.")

print("\nRatings of the movies:")
for movie, rating in ratings.items():
    print(f"{movie}: {rating}")

Please rate the following movies out of 10:
Rate 'Stiff Upper Lips': 6
Rate 'Dancer, Texas Pop. 81': 7
Rate 'Me You and Five Bucks': 7
Rate 'Little Big Top': 5
Rate 'Sardaarji': 
Rate 'One Man's Hero': 
Invalid rating! Please enter a number between 0 and 10.
Invalid rating! Please enter a number between 0 and 10.
Rate 'The Shawshank Redemption': 8
Rate 'There Goes My Baby': 7
Rate 'The Prisoner of Zenda': 7
Rate 'The Godfather': 
Invalid rating! Please enter a number between 0 and 10.
Rate 'Whiplash': 8

Ratings of the movies:
Stiff Upper Lips: 6.0
Dancer, Texas Pop. 81: 7.0
Me You and Five Bucks: 7.0
Little Big Top: 5.0
The Shawshank Redemption: 8.0
There Goes My Baby: 7.0
The Prisoner of Zenda: 7.0
Whiplash: 8.0
